---
- name: Configure VPS
  hosts: webserver
  become: true

  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    # Add more tasks as per your requirements

  roles:
    - common
    - webserver
